In [ ]:
import numpy as np 
import pandas as pd
import re

ok

In [2]:
f=open("whatsapp_chat_with_bache.txt" ,'r',encoding='utf-8')
data=f.read()

In [3]:
print(data)

09/12/2025, 11:46 pm - Messages and calls are end-to-end encrypted. Only people in this chat can read, listen to, or share them. *Learn more*
04/03/2024, 2:25 pm - Huzaifa Uet created group "Bacheeeeeeeee"
04/03/2024, 2:25 pm - You were added
10/12/2025, 12:24 am - M_zee:
13/12/2025, 11:10 pm - Ahmad Khan Bbit:
13/12/2025, 11:10 pm - Ahmad Khan Bbit: @⁨Rayan Bbit⁩ @⁨Abdul Rahman Bbit⁩ @⁨M_zee⁩ @⁨Abdul 🅰️leem Jaat⁩
14/12/2025, 2:03 am - M_zee:
16/12/2025, 9:39 am - Abdul 🅰️leem Jaat: <Media omitted>
16/12/2025, 9:41 am - Abdul 🅰️leem Jaat: Manni 21
16/12/2025, 9:41 am - Abdul 🅰️leem Jaat: Rayan 24
16/12/2025, 9:41 am - Abdul 🅰️leem Jaat: Muazzam 27
16/12/2025, 9:41 am - Abdul 🅰️leem Jaat: Rizwan 20
16/12/2025, 9:41 am - Abdul 🅰️leem Jaat: Aleem 15
16/12/2025, 9:41 am - Abdul 🅰️leem Jaat: Huzaifa 13
16/12/2025, 10:07 am - Abdul Rahman Bbit: Bara yak ha
16/12/2025, 10:07 am - Abdul Rahman Bbit: Bara yak ha
16/12/2025, 10:07 am - Abdul Rahman Bbit: Bara yak ha
16/12/2025, 10:07 am - Abdul Rahman Bbit: Bara yak ha
16/12/2025, 10:07 am - Abdul Rahman Bbit: Bara yak ha Ahmad bi
16/12/2025, 10:13 am - Abdul Rahman Bbit: @⁨Ahmad Khan Bbit⁩ @⁨Abdul 🅰️leem Jaat⁩ @⁨Huzaifa Uet⁩ @⁨M_zee⁩ @⁨Rayan Bbit⁩ @⁨M Rizwan Townshp⁩
Baray yak ho tum sb
16/12/2025, 10:20 am - Abdul 🅰️leem Jaat: <Media omitted>
16/12/2025, 10:39 am - Abdul Rahman Bbit: Phir bi to yak ha
16/12/2025, 10:43 am - Abdul 🅰️leem Jaat: <Media omitted>
16/12/2025, 2:43 pm - Huzaifa Uet: Mashaallah
16/12/2025, 2:48 pm - Abdul Rahman Bbit: Tu to bohat bara yak ha
17/12/2025, 7:19 pm - M_zee: Baber...king
 abuuuuuuuuu 🥳
17/12/2025, 8:37 pm - Abdul 🅰️leem Jaat: <Media omitted>
19/12/2025, 6:28 pm - Abdul Rahman Bbit: <Media omitted>
19/12/2025, 6:28 pm - Abdul Rahman Bbit: Now some haters will say it is edited 🙂
@⁨Ahmad Khan Bbit⁩ @⁨Abdul 🅰️leem Jaat⁩ @⁨Huzaifa Uet⁩ @⁨M_zee⁩ @⁨Rayan Bbit⁩ @⁨M Rizwan Townshp⁩
21/12/2025, 6:15 pm - Abdul Rahman Bbit:
21/12/2025, 6:15 pm - Abdul Rahman Bbit: <Media omitted>
21/12/2025, 6:15 pm - Abdul Rahman Bbit: <Media omitted>
21/12/2025, 6:15 pm - Abdul Rahman Bbit: <Media omitted>
21/12/2025, 6:15 pm - Abdul Rahman Bbit: <Media omitted>
21/12/2025, 6:15 pm - Abdul Rahman Bbit: <Media omitted>
21/12/2025, 6:15 pm - Abdul Rahman Bbit: <Media omitted>
21/12/2025, 6:15 pm - Abdul Rahman Bbit: Yeh jo ma'am ny voice bhaiji wo questions hain
21/12/2025, 6:15 pm - Abdul Rahman Bbit: Kuch galat huwa meri zimadari niii
21/12/2025, 6:16 pm - M Rizwan Townshp: Wah maani
21/12/2025, 6:16 pm - Abdul Rahman Bbit: Wah rizwan😂😂😂
21/12/2025, 7:53 pm - Abdul 🅰️leem Jaat: Wah yar manni level hai tera
21/12/2025, 7:53 pm - Abdul Rahman Bbit: Amb krwa lo
21/12/2025, 7:53 pm - Abdul Rahman Bbit: Mein BC kaisay poohanchun 8 bajay
21/12/2025, 7:53 pm - Abdul Rahman Bbit: 😂😂😂
21/12/2025, 11:27 pm - Abdul 🅰️leem Jaat: Kia bat hai
21/12/2025, 11:28 pm - Abdul Rahman Bbit: Apki bi kia baat ha
27/12/2025, 8:08 pm - Ahmad Khan Bbit: <Media omitted>
27/12/2025, 8:08 pm - Ahmad Khan Bbit: @⁨Abdul Rahman Bbit⁩ @⁨Abdul 🅰️leem Jaat⁩ @⁨M_zee⁩ @⁨Rayan Bbit⁩ @⁨M Rizwan Townshp⁩
27/12/2025, 8:08 pm - Ahmad Khan Bbit: Listen till end
27/12/2025, 8:08 pm - Abdul Rahman Bbit: 😂😂😂
27/12/2025, 8:08 pm - Rayan Bbit: 😂😂
27/12/2025, 8:09 pm - Abdul 🅰️leem Jaat: Ya tu ny voice change ki hai
27/12/2025, 8:09 pm - Abdul 🅰️leem Jaat: Ya nhi thi
27/12/2025, 8:09 pm - Abdul 🅰️leem Jaat: 😭😭😂😂🤧
27/12/2025, 8:09 pm - Rayan Bbit: Original h
27/12/2025, 8:10 pm - Ahmad Khan Bbit: Bhaii mein ne ki hoti mera account atta opr jese maani ka ayya thaa
27/12/2025, 8:10 pm - Rayan Bbit: Hn wohi
27/12/2025, 8:10 pm - Abdul 🅰️leem Jaat: <Media omitted>
27/12/2025, 8:11 pm - Abdul Rahman Bbit: @⁨Huzaifa Uet⁩ yeh kuch ziada hogya
27/12/2025, 8:12 pm - Abdul Rahman Bbit: 😂😂😂
27/12/2025, 8:12 pm - Abdul Rahman Bbit: Hn hn dy do rishta
27/12/2025, 8:12 pm - Ahmad Khan Bbit: Uncle ko mna kr yrr
27/12/2025, 8:12 pm - Rayan Bbit: Bachpan ma zyadti😭
27/12/2025, 8:12 pm - Abdul Rahman Bbit: Kia pta abhi bi karobar mein koi hisaab LG jata ho
27/12/2025, 8:13 pm - Abdul Rahman Bbit: Krny dy it's business bro
27/12/2025, 8:13 pm - Rayan Bbit: 😂
27/12/2025, 8:17 pm - Huzaifa Uet: 😂😂😂Bhai WO mere aba G Hain me nhi so
27/12/2025, 8:18 pm - Ahmad Khan Bbit: Atleast humaara paigham unn tak puhncha dyy
27/12/2025, 8:18 pm - Rayan Bbit: Abba g ko kaho ye kis field ma aagye hain ap😢
27/12/2025, 8:21 pm - Huzaifa Uet: Harami insan khudi voice lgayi h tune itna mujhe pta
27/12/2025, 8:21 pm - Rayan Bbit: Dobara dekh video
27/12/2025, 8:22 pm - Rayan Bbit: Tere daddy ka naam araha h neche watermark ma😭
27/12/2025, 8:22 pm - Ahmad Khan Bbit: Oo shappar insaan agr mein ne lgayi hotii mera account ataa oprr
27/12/2025, 8:22 pm - Ahmad Khan Bbit: Ghorr se account parhhh
27/12/2025, 8:27 pm - Huzaifa Uet: Harami insan mne Uske account SE Dekhi h harami
27/12/2025, 8:27 pm - Ahmad Khan Bbit: Kia mtlb???
27/12/2025, 9:01 pm - Abdul Rahman Bbit: Tu hum ny kia kha
27/12/2025, 9:02 pm - Abdul Rahman Bbit: Dosaray account sy daikhi na
29/12/2025, 1:49 pm - M_zee: https://www.instagram.com/humire.official?igsh=MTdweHl1Y2h3cjVlbg==
29/12/2025, 1:49 pm - M_zee: https://www.tiktok.com/@humire.official?_r=1&_t=ZS-92Ze5g34hDk
29/12/2025, 1:49 pm - M_zee: Bachoo follow like and comments thoko
29/12/2025, 3:08 pm - Abdul Rahman Bbit: Main grp mein bhaijo
31/12/2025, 7:02 pm - Abdul Rahman Bbit: <Media omitted>
31/12/2025, 7:02 pm - Abdul Rahman Bbit: Follow plz
05/01/2026, 2:06 pm - Abdul Rahman Bbit: <Media omitted>
05/01/2026, 2:06 pm - Abdul Rahman Bbit: <Media omitted>
07/01/2026, 11:05 pm - Ahmad Khan Bbit: <Media omitted>
07/01/2026, 11:05 pm - Ahmad Khan Bbit: <Media omitted>
07/01/2026, 11:05 pm - Ahmad Khan Bbit: <Media omitted>
07/01/2026, 11:05 pm - Ahmad Khan Bbit: <Media omitted>
07/01/2026, 11:05 pm - Ahmad Khan Bbit: <Media omitted>
07/01/2026, 11:05 pm - Ahmad Khan Bbit: <Media omitted>
07/01/2026, 11:05 pm - Ahmad Khan Bbit: <Media omitted>
07/01/2026, 11:05 pm - Ahmad Khan Bbit: <Media omitted>
07/01/2026, 11:05 pm - Ahmad Khan Bbit: <Media omitted>
07/01/2026, 11:05 pm - Ahmad Khan Bbit: <Media omitted>
07/01/2026, 11:05 pm - Ahmad Khan Bbit: <Media omitted>
07/01/2026, 11:05 pm - Ahmad Khan Bbit: <Media omitted>
07/01/2026, 11:05 pm - Ahmad Khan Bbit: <Media omitted>
08/01/2026, 7:14 pm - Huzaifa Uet: https://chatgpt.com/share/695fbb9e-7b74-8008-aa8f-6e52e021b18a
08/01/2026, 10:24 pm - Rayan Bbit: <Media omitted>
08/01/2026, 10:27 pm - Rayan Bbit: <Media omitted>
08/01/2026, 10:45 pm - Rayan Bbit: <Media omitted>
08/01/2026, 10:51 pm - Rayan Bbit: <Media omitted>
08/01/2026, 10:51 pm - Rayan Bbit: Surah Saba
08/01/2026, 10:51 pm - Rayan Bbit: Surah Fatir
08/01/2026, 11:04 pm - Rayan Bbit: <Media omitted>
08/01/2026, 11:05 pm - Rayan Bbit: Surah yasin
08/01/2026, 11:13 pm - Rayan Bbit: .
08/01/2026, 11:21 pm - M_zee: <Media omitted>
08/01/2026, 11:23 pm - M_zee: <Media omitted>
08/01/2026, 11:23 pm - M_zee: <Media omitted>
08/01/2026, 11:32 pm - Huzaifa Uet: <Media omitted>
08/01/2026, 11:32 pm - Huzaifa Uet: Important for anyone who is studying from my link
08/01/2026, 11:46 pm - Rayan Bbit: <Media omitted>
08/01/2026, 11:47 pm - Rayan Bbit: Surah As Safat
09/01/2026, 12:09 am - Rayan Bbit: <Media omitted>
09/01/2026, 12:10 am - Rayan Bbit: Surah Az Zumar
09/01/2026, 12:30 am - Rayan Bbit: <Media omitted>
09/01/2026, 12:31 am - Rayan Bbit: Surah momin
09/01/2026, 1:01 am - Ahmad Khan Bbit: 💋
09/01/2026, 1:43 am - M_zee:
09/01/2026, 1:43 am - M_zee: <Media omitted>
09/01/2026, 1:43 am - M_zee: <Media omitted>
09/01/2026, 1:43 am - M_zee: <Media omitted>
09/01/2026, 1:43 am - M_zee: <Media omitted>
09/01/2026, 1:43 am - M_zee: You deleted this message
09/01/2026, 1:43 am - M_zee: <Media omitted>
09/01/2026, 1:43 am - M_zee: <Media omitted>
09/01/2026, 1:43 am - M_zee: <Media omitted>
09/01/2026, 1:43 am - M_zee: <Media omitted>
09/01/2026, 1:43 am - M_zee: <Media omitted>
09/01/2026, 1:43 am - M_zee: <Media omitted>
09/01/2026, 1:43 am - M_zee: <Media omitted>
09/01/2026, 1:43 am - M_zee: You deleted this message
09/01/2026, 1:43 am - M_zee: <Media omitted>
09/01/2026, 1:43 am - M_zee: <Media omitted>
09/01/2026, 11:26 am - M_zee: <Media omitted>
09/01/2026, 11:37 am - M Rizwan Townshp: <Media omitted>
09/01/2026, 11:44 am - Ahmad Khan Bbit: Bhai paper k baad hi bhj detaa
09/01/2026, 11:45 am - M Rizwan Townshp: Mujhy  kuch time phely mila ga
09/01/2026, 11:49 am - Ahmad Khan Bbit: Yh msg uss bndy ko forward krdy
09/01/2026, 11:49 am - M Rizwan Townshp: Konsa bndy ko
10/01/2026, 4:04 pm - Ahmad Khan Bbit: Below is **a very easy, simple-language explanation of *every topic* from *every slide* of your file "Chapter 4 — Requirements Engineering"**.
I’ve rewritten everything in **clear, student-friendly words** so you can prepare for exams, assignments, viva, or presentations.

---

# **CHAPTER 4 – REQUIREMENTS ENGINEERING**

### *Full Explanation in Easy Words*

---

# **1. What is Requirements Engineering?**

Requirements Engineering (RE) is the process of **understanding what the customer wants** from a software system and **what limitations or rules** the system must follow.

It includes:

* Identifying system services (features)
* Identifying constraints (rules, limits)
* Writing them clearly
* Checking they are correct
* Updating when changes happen

The final output is called **System Requirements**.

---

# **2. What is a Requirement?**

A requirement can be:

* A simple, vague statement (e.g., “The system must be fast.”)
* Or a detailed technical statement (e.g., “Response time must be under 2 seconds.”)

Requirements serve two purposes:

1. **Creating project proposals** (so statements are usually flexible)
2. **Creating legal contracts** (requirements must be very detailed)

Both are still called “requirements.”

---

# **3. Types of Requirements**

### **A. User Requirements**

* Written in simple language
* For customers/end-users
* Describe *what* the users want
* No technical details

### **B. System Requirements**

* Detailed and technical
* For developers and designers
* Explains *how* the system will work
* Includes every function, rule, and constraint

---

# **4. System Stakeholders**

Stakeholders = Anyone affected by the system.

Types:

1. **End users** – People who will use the system daily
2. **System managers** – Maintain and operate the system
3. **System owners** – Pay for and control the project
4. **External stakeholders** – Government, partners, regulators, etc.

---

# **5. Functional vs Non-functional Requirements**

### **Functional Requirements**

* What the system should *do*
* Example: “System must allow login.”

Also includes how system should react to inputs and conditions.

### **Non-functional Requirements**

* Quality of the system
* Constraints on performance, security, safety, speed, usability, etc.
* Often more important because if they fail, the system may be useless

### **Domain Requirements**

* Rules from the industry/environment
* Example: Banking system must follow financial regulations.

---

# **6. Problems in Requirements**

### **Imprecision (Not clear enough)**

If functional requirements are unclear, users and developers can interpret them differently → leads to mistakes.

### **Completeness**

All required features must be included.

### **Consistency**

No contradictions between requirements.

In real life, **perfect completeness and consistency are almost impossible**.

---

# **7. Types of Non-functional Requirements**

### **A. Product Requirements**

How the system should behave
Examples:

* Reliability
* Speed
* Performance

### **B. Organisational Requirements**

Based on company policies
Examples:

* Must use a specific programming language
* Must follow ISO standards

### **C. External Requirements**

Based on outside rules
Examples:

* Government laws
* Data privacy rules
* Industry standards

---

# **8. Metrics for Non-functional Requirements**

Non-functional requirements should be measurable.

Examples:

* “System must respond in < 2 seconds.”
* “Uptime must be 99.9%.”

---

# **9. Requirements Engineering Process**

Every RE process includes 4 major activities:

1. **Requirements Elicitation** – Finding out what users want
2. **Requirements Analysis** – Understanding and organizing requirements
3. **Requirements Validation** – Checking if requirements are correct
4. **Requirements Management** – Controlling changes over time

This process is **iterative (repeats like a cycle/spiral).**

---

# **10. Requirements Elicitation & Analysis**

Also called **requirements discovery**.

Engineers work with stakeholders to:

* Learn domain knowledge
* Find required services
* Understand constraints
* Discover conflicts and missing information

Stakeholders include:

* Users
* Managers
* Domain experts
* Maintenance teams
* External agencies

---

# **11. Steps in Elicitation & Analysis**

1. **Discovery**
   Collecting raw requirements from stakeholders.

2. **Classification & Organization**
   Grouping similar requirements.

3. **Prioritization & Negotiation**
   Deciding which requirements are important and resolving conflicts.

4. **Specification**
   Writing requirements clearly in documents.

---

# **12. Requirements Specification**

This is the step where all requirements are **written down clearly**.

Includes:

* User requirements (simple language)
* System requirements (technical details)

It is often part of the **contract** between client and developer.

---

# **13. Ways of Writing Requirements**

### 1. **Structured Specifications**

* Uses fixed formats or templates
* Reduces confusion
* Good for technical/embedded systems
* Not very flexible for business systems

### 2. **Tabular Specifications**

* Useful for multiple conditions and actions
* Example: Insulin pump calculations in a table

### 3. **Use Cases**

* Part of UML
* Describe the interaction between user and system
* Include:

  * Actors (users)
  * Steps of interaction
* Can be expanded using sequence diagrams

---

# **14. Software Requirements Document (SRS)**

SRS is the **official document** that describes everything the system must do.

Contains:

* User requirements
* System requirements

Important:
SRS describes **WHAT**, not **HOW** the system should be built.

Users of SRS include:

* Customers
* Managers
* Designers
* Testers
* Maintainers

Structure often includes:

* Introduction
* General description
* Specific requirements
* Appendices
* Index

---

# **15. Requirements Validation**

Ensuring that requirements truly represent what the customer wants.

Why?
Because fixing a requirements error later can cost **up to 100x more**.

### Validation Checks:

* **Validity:** Do they solve the customer’s problem?
* **Consistency:** No conflicts?
* **Completeness:** Nothing missing?
* **Realism:** Can it be implemented?
* **Verifiability:** Can we test it?

### Validation Techniques:

1. Reviews (manual checking)
2. Prototyping
3. Test-case generation

---

# **16. Requirements Change**

Requirements often change because:

* Business environment changes
* New hardware/software appears
* User needs change
* Laws or regulations change
* Different user groups have conflicting needs

Large systems always go through change.

---

# **17. Requirements Change Management**

3-step process:

### **1. Problem Analysis & Change Specification**

* Understand the request
* Check if it is valid
* Clarify the change

### **2. Change Analysis & Costing**

* Evaluate impact
* Check related requirements (traceability)
* Decide if change should be accepted

### **3. Change Implementation**

* Update requirements document
* Update design & code (if needed)

Documents must be organized so updates are easy.

---

# **DONE!**

If you want, I can also make:
✅ Summary notes
✅ MCQs
✅ Long questions answers
✅ PPT for presentation
✅ Mind map
Just tell me!
10/01/2026, 4:04 pm - Ahmad Khan Bbit: Perfect 👍 thanks for clarifying.
Now I’ll explain **EVERY SLIDE / EVERY TOPIC** from your PPT **in full detail**, using **very easy language**, **examples**, and **concept-by-concept depth**.
This is suitable for **exams, viva, assignments, and presentations**.

---

# **Chapter 5 – System Modeling (FULL DETAILED EXPLANATION)**

---

## **1. What is System Modeling? (In Depth)**

System modeling is the process of **creating simplified representations (models)** of a real system before actually building it.

### Why we do system modeling?

* Real systems are **too complex**
* Models help us:

  * Understand how the system should work
  * Find errors early
  * Explain ideas to customers and team members
  * Improve communication between developers and stakeholders

### What is a model?

A **model** is:

* Not the real system
* A **simplified picture**
* Focuses only on **important details**

Example:
Before constructing a building, engineers draw **blueprints**.
Similarly, before developing software, engineers create **system models**.

---

## **2. Use of UML in System Modeling**

Most system models are created using **UML (Unified Modeling Language)**.

### Why UML?

* UML is a **standard language**
* Easy to understand globally
* Uses diagrams instead of long text
* Supports different system views

UML helps:

* Analysts understand system functionality
* Developers design systems
* Customers visualize the system

---

## **3. Planned System Models (Detailed Explanation)**

Planned system models are used **throughout software development**, especially during **requirements engineering**.

### During Requirements Engineering:

* Models help explain:

  * What the system will do
  * What it will not do
* Stakeholders can:

  * Review requirements
  * Suggest changes

### During Design:

* Engineers discuss:

  * System structure
  * Possible solutions
* Models act as **design documents**

### During Implementation:

* In **Model-Driven Engineering**, models can:

  * Automatically generate code
  * Reduce manual coding
  * Reduce errors

👉 Models are not just drawings — they guide the **entire development process**.

---

## **4. System Perspectives (Very Important Topic)**

A single model cannot explain everything.
Therefore, systems are viewed from **different perspectives**.

---

### **4.1 External Perspective (Context View)**

* Shows the **environment** of the system
* Focuses on:

  * External users
  * External systems
* Defines **system boundaries**

Example:

* ATM system
* Bank database is outside
* Customer is outside

👉 Answers: **What is outside the system?**

---

### **4.2 Interaction Perspective**

* Shows interactions:

  * User ↔ System
  * System ↔ System
  * Component ↔ Component

Used to:

* Identify user requirements
* Understand communication flow

Example:

* User logs in
* System verifies password
* Database confirms user

👉 Answers: **Who interacts with the system and how?**

---

### **4.3 Structural Perspective**

* Shows system **internal structure**
* Includes:

  * Classes
  * Components
  * Data structures

Example:

* Student class
* Course class
* Enrollment relationship

👉 Answers: **How is the system organized?**

---

### **4.4 Behavioral Perspective**

* Shows **dynamic behavior**
* Focuses on:

  * Events
  * Responses
  * State changes

Example:

* Microwave oven:

  * Idle → Cooking → Finished

👉 Answers: **How does the system behave over time?**

---

## **5. UML Diagram Types (Deep Explanation)**

### **Activity Diagram**

* Similar to a flowchart
* Shows step-by-step process
* Used for:

  * Business processes
  * Workflows

Example:

* Online order process

---

### **Use Case Diagram**

* Shows what users can do
* Contains:

  * Actors
  * Use cases

Example:

* Login
* Register
* View details

---

### **Sequence Diagram**

* Shows message flow
* Focus on **order of actions**
* Uses arrows and lifelines

Example:

* User requests data
* System fetches from database

---

### **Class Diagram**

* Shows:

  * Classes
  * Attributes
  * Methods
  * Relationships


In [4]:
print(type(data))

<class 'str'>

In [5]:
# mention regular expression pattern of date and time
pattern = r'\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s?[APap][Mm]\s-\s'

In [6]:
messages = re.split(pattern, data)[1:]

In [7]:
messages

['Messages and calls are end-to-end encrypted. Only people in this chat can read, listen to, or share them. *Learn more*\n',
 'Huzaifa Uet created group "Bacheeeeeeeee"\n',
 'You were added\n',
 'M_zee: \n',
 'Ahmad Khan Bbit: \n',
 'Ahmad Khan Bbit: @\u2068Rayan Bbit\u2069 @\u2068Abdul Rahman Bbit\u2069 @\u2068M_zee\u2069 @\u2068Abdul 🅰️leem Jaat\u2069\n',
 'M_zee: \n',
 'Abdul 🅰️leem Jaat: <Media omitted>\n',
 'Abdul 🅰️leem Jaat: Manni 21\n',
 'Abdul 🅰️leem Jaat: Rayan 24\n',
 'Abdul 🅰️leem Jaat: Muazzam 27\n',
 'Abdul 🅰️leem Jaat: Rizwan 20\n',
 'Abdul 🅰️leem Jaat: Aleem 15\n',
 'Abdul 🅰️leem Jaat: Huzaifa 13\n',
 'Abdul Rahman Bbit: Bara yak ha\n',
 'Abdul Rahman Bbit: Bara yak ha\n',
 'Abdul Rahman Bbit: Bara yak ha\n',
 'Abdul Rahman Bbit: Bara yak ha\n',
 'Abdul Rahman Bbit: Bara yak ha Ahmad bi\n',
 'Abdul Rahman Bbit: @\u2068Ahmad Khan Bbit\u2069 @\u2068Abdul 🅰️leem Jaat\u2069 @\u2068Huzaifa Uet\u2069 @\u2068M_zee\u2069 @\u2068Rayan Bbit\u2069 @\u2068M Rizwan Townshp\u2069 \nBaray yak ho tum sb\n',
 'Abdul 🅰️leem Jaat: <Media omitted>\n',
 'Abdul Rahman Bbit: Phir bi to yak ha\n',
 'Abdul 🅰️leem Jaat: <Media omitted>\n',
 'Huzaifa Uet: Mashaallah\n',
 'Abdul Rahman Bbit: Tu to bohat bara yak ha\n',
 'M_zee: Baber...king \n abuuuuuuuuu 🥳\n',
 'Abdul 🅰️leem Jaat: <Media omitted>\n',
 'Abdul Rahman Bbit: <Media omitted>\n',
 'Abdul Rahman Bbit: Now some haters will say it is edited 🙂\n@\u2068Ahmad Khan Bbit\u2069 @\u2068Abdul 🅰️leem Jaat\u2069 @\u2068Huzaifa Uet\u2069 @\u2068M_zee\u2069 @\u2068Rayan Bbit\u2069 @\u2068M Rizwan Townshp\u2069\n',
 'Abdul Rahman Bbit: \n',
 'Abdul Rahman Bbit: <Media omitted>\n',
 'Abdul Rahman Bbit: <Media omitted>\n',
 'Abdul Rahman Bbit: <Media omitted>\n',
 'Abdul Rahman Bbit: <Media omitted>\n',
 'Abdul Rahman Bbit: <Media omitted>\n',
 'Abdul Rahman Bbit: <Media omitted>\n',
 "Abdul Rahman Bbit: Yeh jo ma'am ny voice bhaiji wo questions hain\n",
 'Abdul Rahman Bbit: Kuch galat huwa meri zimadari niii\n',
 'M Rizwan Townshp: Wah maani\n',
 'Abdul Rahman Bbit: Wah rizwan😂😂😂\n',
 'Abdul 🅰️leem Jaat: Wah yar manni level hai tera\n',
 'Abdul Rahman Bbit: Amb krwa lo\n',
 'Abdul Rahman Bbit: Mein BC kaisay poohanchun 8 bajay\n',
 'Abdul Rahman Bbit: 😂😂😂\n',
 'Abdul 🅰️leem Jaat: Kia bat hai\n',
 'Abdul Rahman Bbit: Apki bi kia baat ha\n',
 'Ahmad Khan Bbit: <Media omitted>\n',
 'Ahmad Khan Bbit: @\u2068Abdul Rahman Bbit\u2069 @\u2068Abdul 🅰️leem Jaat\u2069 @\u2068M_zee\u2069 @\u2068Rayan Bbit\u2069 @\u2068M Rizwan Townshp\u2069\n',
 'Ahmad Khan Bbit: Listen till end\n',
 'Abdul Rahman Bbit: 😂😂😂\n',
 'Rayan Bbit: 😂😂\n',
 'Abdul 🅰️leem Jaat: Ya tu ny voice change ki hai\n',
 'Abdul 🅰️leem Jaat: Ya nhi thi\n',
 'Abdul 🅰️leem Jaat: 😭😭😂😂🤧\n',
 'Rayan Bbit: Original h\n',
 'Ahmad Khan Bbit: Bhaii mein ne ki hoti mera account atta opr jese maani ka ayya thaa\n',
 'Rayan Bbit: Hn wohi\n',
 'Abdul 🅰️leem Jaat: <Media omitted>\n',
 'Abdul Rahman Bbit: @\u2068Huzaifa Uet\u2069 yeh kuch ziada hogya\n',
 'Abdul Rahman Bbit: 😂😂😂\n',
 'Abdul Rahman Bbit: Hn hn dy do rishta\n',
 'Ahmad Khan Bbit: Uncle ko mna kr yrr\n',
 'Rayan Bbit: Bachpan ma zyadti😭\n',
 'Abdul Rahman Bbit: Kia pta abhi bi karobar mein koi hisaab LG jata ho\n',
 "Abdul Rahman Bbit: Krny dy it's business bro\n",
 'Rayan Bbit: 😂\n',
 'Huzaifa Uet: 😂😂😂Bhai WO mere aba G Hain me nhi so\n',
 'Ahmad Khan Bbit: Atleast humaara paigham unn tak puhncha dyy\n',
 'Rayan Bbit: Abba g ko kaho ye kis field ma aagye hain ap😢\n',
 'Huzaifa Uet: Harami insan khudi voice lgayi h tune itna mujhe pta\n',
 'Rayan Bbit: Dobara dekh video\n',
 'Rayan Bbit: Tere daddy ka naam araha h neche watermark ma😭\n',
 'Ahmad Khan Bbit: Oo shappar insaan agr mein ne lgayi hotii mera account ataa oprr\n',
 'Ahmad Khan Bbit: Ghorr se account parhhh\n',
 'Huzaifa Uet: Harami insan mne Uske account SE Dekhi h harami\n',
 'Ahmad Khan Bbit: Kia mtlb???\n',
 'Abdul Rahman Bbit: Tu hum ny kia kha\n',
 'Abdul Rahman Bbit: Dosaray account sy daikhi na\n',
 'M_zee: https://www.instagram.com/humire.official?igsh=MTdweHl1Y2h3cjVlbg==\n',
 'M_zee: https://www.tiktok.com/@humire.official?_r=1&_t=ZS-92Ze5g34hDk\n',
 'M_zee: Bachoo follow like and comments thoko\n',
 'Abdul Rahman Bbit: Main grp mein bhaijo\n',
 'Abdul Rahman Bbit: <Media omitted>\n',
 'Abdul Rahman Bbit: Follow plz\n',
 'Abdul Rahman Bbit: <Media omitted>\n',
 'Abdul Rahman Bbit: <Media omitted>\n',
 'Ahmad Khan Bbit: <Media omitted>\n',
 'Ahmad Khan Bbit: <Media omitted>\n',
 'Ahmad Khan Bbit: <Media omitted>\n',
 'Ahmad Khan Bbit: <Media omitted>\n',
 'Ahmad Khan Bbit: <Media omitted>\n',
 'Ahmad Khan Bbit: <Media omitted>\n',
 'Ahmad Khan Bbit: <Media omitted>\n',
 'Ahmad Khan Bbit: <Media omitted>\n',
 'Ahmad Khan Bbit: <Media omitted>\n',
 'Ahmad Khan Bbit: <Media omitted>\n',
 'Ahmad Khan Bbit: <Media omitted>\n',
 'Ahmad Khan Bbit: <Media omitted>\n',
 'Ahmad Khan Bbit: <Media omitted>\n',
 'Huzaifa Uet: https://chatgpt.com/share/695fbb9e-7b74-8008-aa8f-6e52e021b18a\n',
 'Rayan Bbit: <Media omitted>\n',
 'Rayan Bbit: <Media omitted>\n',
 'Rayan Bbit: <Media omitted>\n',
 'Rayan Bbit: <Media omitted>\n',
 'Rayan Bbit: Surah Saba\n',
 'Rayan Bbit: Surah Fatir\n',
 'Rayan Bbit: <Media omitted>\n',
 'Rayan Bbit: Surah yasin\n',
 'Rayan Bbit: .\n',
 'M_zee: <Media omitted>\n',
 'M_zee: <Media omitted>\n',
 'M_zee: <Media omitted>\n',
 'Huzaifa Uet: <Media omitted>\n',
 'Huzaifa Uet: Important for anyone who is studying from my link\n',
 'Rayan Bbit: <Media omitted>\n',
 'Rayan Bbit: Surah As Safat\n',
 'Rayan Bbit: <Media omitted>\n',
 'Rayan Bbit: Surah Az Zumar\n',
 'Rayan Bbit: <Media omitted>\n',
 'Rayan Bbit: Surah momin\n',
 'Ahmad Khan Bbit: 💋\n',
 'M_zee: \n',
 'M_zee: <Media omitted>\n',
 'M_zee: <Media omitted>\n',
 'M_zee: <Media omitted>\n',
 'M_zee: <Media omitted>\n',
 'M_zee: You deleted this message\n',
 'M_zee: <Media omitted>\n',
 'M_zee: <Media omitted>\n',
 'M_zee: <Media omitted>\n',
 'M_zee: <Media omitted>\n',
 'M_zee: <Media omitted>\n',
 'M_zee: <Media omitted>\n',
 'M_zee: <Media omitted>\n',
 'M_zee: You deleted this message\n',
 'M_zee: <Media omitted>\n',
 'M_zee: <Media omitted>\n',
 'M_zee: <Media omitted>\n',
 'M Rizwan Townshp: <Media omitted>\n',
 'Ahmad Khan Bbit: Bhai paper k baad hi bhj detaa\n',
 'M Rizwan Townshp: Mujhy  kuch time phely mila ga\n',
 'Ahmad Khan Bbit: Yh msg uss bndy ko forward krdy\n',
 'M Rizwan Townshp: Konsa bndy ko\n',
 'Ahmad Khan Bbit: Below is **a very easy, simple-language explanation of *every topic* from *every slide* of your file "Chapter 4 — Requirements Engineering"**.\nI’ve rewritten everything in **clear, student-friendly words** so you can prepare for exams, assignments, viva, or presentations.\n\n---\n\n# **CHAPTER 4 – REQUIREMENTS ENGINEERING**\n\n### *Full Explanation in Easy Words*\n\n---\n\n# **1. What is Requirements Engineering?**\n\nRequirements Engineering (RE) is the process of **understanding what the customer wants** from a software system and **what limitations or rules** the system must follow.\n\nIt includes:\n\n* Identifying system services (features)\n* Identifying constraints (rules, limits)\n* Writing them clearly\n* Checking they are correct\n* Updating when changes happen\n\nThe final output is called **System Requirements**.\n\n---\n\n# **2. What is a Requirement?**\n\nA requirement can be:\n\n* A simple, vague statement (e.g., “The system must be fast.”)\n* Or a detailed technical statement (e.g., “Response time must be under 2 seconds.”)\n\nRequirements serve two purposes:\n\n1. **Creating project proposals** (so statements are usually flexible)\n2. **Creating legal contracts** (requirements must be very detailed)\n\nBoth are still called “requirements.”\n\n---\n\n# **3. Types of Requirements**\n\n### **A. User Requirements**\n\n* Written in simple language\n* For customers/end-users\n* Describe *what* the users want\n* No technical details\n\n### **B. System Requirements**\n\n* Detailed and technical\n* For developers and designers\n* Explains *how* the system will work\n* Includes every function, rule, and constraint\n\n---\n\n# **4. System Stakeholders**\n\nStakeholders = Anyone affected by the system.\n\nTypes:\n\n1. **End users** – People who will use the system daily\n2. **System managers** – Maintain and operate the system\n3. **System owners** – Pay for and control the project\n4. **External stakeholders** – Government, partners, regulators, etc.\n\n---\n\n# **5. Functional vs Non-functional Requirements**\n\n### **Functional Requirements**\n\n* What the system should *do*\n* Example: “System must allow login.”\n\nAlso includes how system should react to inputs and conditions.\n\n### **Non-functional Requirements**\n\n* Quality of the system\n* Constraints on performance, security, safety, speed, usability, etc.\n* Often more important because if they fail, the system may be useless\n\n### **Domain Requirements**\n\n* Rules from the industry/environment\n* Example: Banking system must follow financial regulations.\n\n---\n\n# **6. Problems in Requirements**\n\n### **Imprecision (Not clear enough)**\n\nIf functional requirements are unclear, users and developers can interpret them differently → leads to mistakes.\n\n### **Completeness**\n\nAll required features must be included.\n\n### **Consistency**\n\nNo contradictions between requirements.\n\nIn real life, **perfect completeness and consistency are almost impossible**.\n\n---\n\n# **7. Types of Non-functional Requirements**\n\n### **A. Product Requirements**\n\nHow the system should behave\nExamples:\n\n* Reliability\n* Speed\n* Performance\n\n### **B. Organisational Requirements**\n\nBased on company policies\nExamples:\n\n* Must use a specific programming language\n* Must follow ISO standards\n\n### **C. External Requirements**\n\nBased on outside rules\nExamples:\n\n* Government laws\n* Data privacy rules\n* Industry standards\n\n---\n\n# **8. Metrics for Non-functional Requirements**\n\nNon-functional requirements should be measurable.\n\nExamples:\n\n* “System must respond in < 2 seconds.”\n* “Uptime must be 99.9%.”\n\n---\n\n# **9. Requirements Engineering Process**\n\nEvery RE process includes 4 major activities:\n\n1. **Requirements Elicitation** – Finding out what users want\n2. **Requirements Analysis** – Understanding and organizing requirements\n3. **Requirements Validation** – Checking if requirements are correct\n4. **Requirements Management** – Controlling changes over time\n\nThis process is **iterative (repeats like a cycle/spiral).**\n\n---\n\n# **10. Requirements Elicitation & Analysis**\n\nAlso called **requirements discovery**.\n\nEngineers work with stakeholders to:\n\n* Learn domain knowledge\n* Find required services\n* Understand constraints\n* Discover conflicts and missing information\n\nStakeholders include:\n\n* Users\n* Managers\n* Domain experts\n* Maintenance teams\n* External agencies\n\n---\n\n# **11. Steps in Elicitation & Analysis**\n\n1. **Discovery**\n   Collecting raw requirements from stakeholders.\n\n2. **Classification & Organization**\n   Grouping similar requirements.\n\n3. **Prioritization & Negotiation**\n   Deciding which requirements are important and resolving conflicts.\n\n4. **Specification**\n   Writing requirements clearly in documents.\n\n---\n\n# **12. Requirements Specification**\n\nThis is the step where all requirements are **written down clearly**.\n\nIncludes:\n\n* User requirements (simple language)\n* System requirements (technical details)\n\nIt is often part of the **contract** between client and developer.\n\n---\n\n# **13. Ways of Writing Requirements**\n\n### 1. **Structured Specifications**\n\n* Uses fixed formats or templates\n* Reduces confusion\n* Good for technical/embedded systems\n* Not very flexible for business systems\n\n### 2. **Tabular Specifications**\n\n* Useful for multiple conditions and actions\n* Example: Insulin pump calculations in a table\n\n### 3. **Use Cases**\n\n* Part of UML\n* Describe the interaction between user and system\n* Include:\n\n  * Actors (users)\n  * Steps of interaction\n* Can be expanded using sequence diagrams\n\n---\n\n# **14. Software Requirements Document (SRS)**\n\nSRS is the **official document** that describes everything the system must do.\n\nContains:\n\n* User requirements\n* System requirements\n\nImportant:\nSRS describes **WHAT**, not **HOW** the system should be built.\n\nUsers of SRS include:\n\n* Customers\n* Managers\n* Designers\n* Testers\n* Maintainers\n\nStructure often includes:\n\n* Introduction\n* General description\n* Specific requirements\n* Appendices\n* Index\n\n---\n\n# **15. Requirements Validation**\n\nEnsuring that requirements truly represent what the customer wants.\n\nWhy?\nBecause fixing a requirements error later can cost **up to 100x more**.\n\n### Validation Checks:\n\n* **Validity:** Do they solve the customer’s problem?\n* **Consistency:** No conflicts?\n* **Completeness:** Nothing missing?\n* **Realism:** Can it be implemented?\n* **Verifiability:** Can we test it?\n\n### Validation Techniques:\n\n1. Reviews (manual checking)\n2. Prototyping\n3. Test-case generation\n\n---\n\n# **16. Requirements Change**\n\nRequirements often change because:\n\n* Business environment changes\n* New hardware/software appears\n* User needs change\n* Laws or regulations change\n* Different user groups have conflicting needs\n\nLarge systems always go through change.\n\n---\n\n# **17. Requirements Change Management**\n\n3-step process:\n\n### **1. Problem Analysis & Change Specification**\n\n* Understand the request\n* Check if it is valid\n* Clarify the change\n\n### **2. Change Analysis & Costing**\n\n* Evaluate impact\n* Check related requirements (traceability)\n* Decide if change should be accepted\n\n### **3. Change Implementation**\n\n* Update requirements document\n* Update design & code (if needed)\n\nDocuments must be organized so updates are easy.\n\n---\n\n# **DONE!**\n\nIf you want, I can also make:\n✅ Summary notes\n✅ MCQs\n✅ Long questions answers\n✅ PPT for presentation\n✅ Mind map\nJust tell me!\n',

In [8]:
dates=re.findall(pattern,data)

In [9]:
dates

['09/12/2025, 11:46\u202fpm - ',
 '04/03/2024, 2:25\u202fpm - ',
 '04/03/2024, 2:25\u202fpm - ',
 '10/12/2025, 12:24\u202fam - ',
 '13/12/2025, 11:10\u202fpm - ',
 '13/12/2025, 11:10\u202fpm - ',
 '14/12/2025, 2:03\u202fam - ',
 '16/12/2025, 9:39\u202fam - ',
 '16/12/2025, 9:41\u202fam - ',
 '16/12/2025, 9:41\u202fam - ',
 '16/12/2025, 9:41\u202fam - ',
 '16/12/2025, 9:41\u202fam - ',
 '16/12/2025, 9:41\u202fam - ',
 '16/12/2025, 9:41\u202fam - ',
 '16/12/2025, 10:07\u202fam - ',
 '16/12/2025, 10:07\u202fam - ',
 '16/12/2025, 10:07\u202fam - ',
 '16/12/2025, 10:07\u202fam - ',
 '16/12/2025, 10:07\u202fam - ',
 '16/12/2025, 10:13\u202fam - ',
 '16/12/2025, 10:20\u202fam - ',
 '16/12/2025, 10:39\u202fam - ',
 '16/12/2025, 10:43\u202fam - ',
 '16/12/2025, 2:43\u202fpm - ',
 '16/12/2025, 2:48\u202fpm - ',
 '17/12/2025, 7:19\u202fpm - ',
 '17/12/2025, 8:37\u202fpm - ',
 '19/12/2025, 6:28\u202fpm - ',
 '19/12/2025, 6:28\u202fpm - ',
 '21/12/2025, 6:15\u202fpm - ',
 '21/12/2025, 6:15\u202fpm - ',
 '21/12/2025, 6:15\u202fpm - ',
 '21/12/2025, 6:15\u202fpm - ',
 '21/12/2025, 6:15\u202fpm - ',
 '21/12/2025, 6:15\u202fpm - ',
 '21/12/2025, 6:15\u202fpm - ',
 '21/12/2025, 6:15\u202fpm - ',
 '21/12/2025, 6:15\u202fpm - ',
 '21/12/2025, 6:16\u202fpm - ',
 '21/12/2025, 6:16\u202fpm - ',
 '21/12/2025, 7:53\u202fpm - ',
 '21/12/2025, 7:53\u202fpm - ',
 '21/12/2025, 7:53\u202fpm - ',
 '21/12/2025, 7:53\u202fpm - ',
 '21/12/2025, 11:27\u202fpm - ',
 '21/12/2025, 11:28\u202fpm - ',
 '27/12/2025, 8:08\u202fpm - ',
 '27/12/2025, 8:08\u202fpm - ',
 '27/12/2025, 8:08\u202fpm - ',
 '27/12/2025, 8:08\u202fpm - ',
 '27/12/2025, 8:08\u202fpm - ',
 '27/12/2025, 8:09\u202fpm - ',
 '27/12/2025, 8:09\u202fpm - ',
 '27/12/2025, 8:09\u202fpm - ',
 '27/12/2025, 8:09\u202fpm - ',
 '27/12/2025, 8:10\u202fpm - ',
 '27/12/2025, 8:10\u202fpm - ',
 '27/12/2025, 8:10\u202fpm - ',
 '27/12/2025, 8:11\u202fpm - ',
 '27/12/2025, 8:12\u202fpm - ',
 '27/12/2025, 8:12\u202fpm - ',
 '27/12/2025, 8:12\u202fpm - ',
 '27/12/2025, 8:12\u202fpm - ',
 '27/12/2025, 8:12\u202fpm - ',
 '27/12/2025, 8:13\u202fpm - ',
 '27/12/2025, 8:13\u202fpm - ',
 '27/12/2025, 8:17\u202fpm - ',
 '27/12/2025, 8:18\u202fpm - ',
 '27/12/2025, 8:18\u202fpm - ',
 '27/12/2025, 8:21\u202fpm - ',
 '27/12/2025, 8:21\u202fpm - ',
 '27/12/2025, 8:22\u202fpm - ',
 '27/12/2025, 8:22\u202fpm - ',
 '27/12/2025, 8:22\u202fpm - ',
 '27/12/2025, 8:27\u202fpm - ',
 '27/12/2025, 8:27\u202fpm - ',
 '27/12/2025, 9:01\u202fpm - ',
 '27/12/2025, 9:02\u202fpm - ',
 '29/12/2025, 1:49\u202fpm - ',
 '29/12/2025, 1:49\u202fpm - ',
 '29/12/2025, 1:49\u202fpm - ',
 '29/12/2025, 3:08\u202fpm - ',
 '31/12/2025, 7:02\u202fpm - ',
 '31/12/2025, 7:02\u202fpm - ',
 '05/01/2026, 2:06\u202fpm - ',
 '05/01/2026, 2:06\u202fpm - ',
 '07/01/2026, 11:05\u202fpm - ',
 '07/01/2026, 11:05\u202fpm - ',
 '07/01/2026, 11:05\u202fpm - ',
 '07/01/2026, 11:05\u202fpm - ',
 '07/01/2026, 11:05\u202fpm - ',
 '07/01/2026, 11:05\u202fpm - ',
 '07/01/2026, 11:05\u202fpm - ',
 '07/01/2026, 11:05\u202fpm - ',
 '07/01/2026, 11:05\u202fpm - ',
 '07/01/2026, 11:05\u202fpm - ',
 '07/01/2026, 11:05\u202fpm - ',
 '07/01/2026, 11:05\u202fpm - ',
 '07/01/2026, 11:05\u202fpm - ',
 '08/01/2026, 7:14\u202fpm - ',
 '08/01/2026, 10:24\u202fpm - ',
 '08/01/2026, 10:27\u202fpm - ',
 '08/01/2026, 10:45\u202fpm - ',
 '08/01/2026, 10:51\u202fpm - ',
 '08/01/2026, 10:51\u202fpm - ',
 '08/01/2026, 10:51\u202fpm - ',
 '08/01/2026, 11:04\u202fpm - ',
 '08/01/2026, 11:05\u202fpm - ',
 '08/01/2026, 11:13\u202fpm - ',
 '08/01/2026, 11:21\u202fpm - ',
 '08/01/2026, 11:23\u202fpm - ',
 '08/01/2026, 11:23\u202fpm - ',
 '08/01/2026, 11:32\u202fpm - ',
 '08/01/2026, 11:32\u202fpm - ',
 '08/01/2026, 11:46\u202fpm - ',
 '08/01/2026, 11:47\u202fpm - ',
 '09/01/2026, 12:09\u202fam - ',
 '09/01/2026, 12:10\u202fam - ',
 '09/01/2026, 12:30\u202fam - ',
 '09/01/2026, 12:31\u202fam - ',
 '09/01/2026, 1:01\u202fam - ',
 '09/01/2026, 1:43\u202fam - ',
 '09/01/2026, 1:43\u202fam - ',
 '09/01/2026, 1:43\u202fam - ',
 '09/01/2026, 1:43\u202fam - ',
 '09/01/2026, 1:43\u202fam - ',
 '09/01/2026, 1:43\u202fam - ',
 '09/01/2026, 1:43\u202fam - ',
 '09/01/2026, 1:43\u202fam - ',
 '09/01/2026, 1:43\u202fam - ',
 '09/01/2026, 1:43\u202fam - ',
 '09/01/2026, 1:43\u202fam - ',
 '09/01/2026, 1:43\u202fam - ',
 '09/01/2026, 1:43\u202fam - ',
 '09/01/2026, 1:43\u202fam - ',
 '09/01/2026, 1:43\u202fam - ',
 '09/01/2026, 1:43\u202fam - ',
 '09/01/2026, 11:26\u202fam - ',
 '09/01/2026, 11:37\u202fam - ',
 '09/01/2026, 11:44\u202fam - ',
 '09/01/2026, 11:45\u202fam - ',
 '09/01/2026, 11:49\u202fam - ',
 '09/01/2026, 11:49\u202fam - ',
 '10/01/2026, 4:04\u202fpm - ',
 '10/01/2026, 4:04\u202fpm - ',
 '10/01/2026, 4:09\u202fpm - ',
 '10/01/2026, 4:10\u202fpm - ',
 '10/01/2026, 4:12\u202fpm - ',
 '13/01/2026, 4:24\u202fpm - ',
 '13/01/2026, 4:24\u202fpm - ',
 '13/01/2026, 4:24\u202fpm - ',
 '13/01/2026, 4:24\u202fpm - ',
 '13/01/2026, 4:24\u202fpm - ',
 '13/01/2026, 4:24\u202fpm - ',
 '13/01/2026, 4:24\u202fpm - ',
 '13/01/2026, 4:24\u202fpm - ',
 '13/01/2026, 4:24\u202fpm - ',
 '13/01/2026, 4:24\u202fpm - ',
 '13/01/2026, 6:15\u202fpm - ',
 '13/01/2026, 6:15\u202fpm - ',
 '13/01/2026, 6:15\u202fpm - ',
 '13/01/2026, 6:15\u202fpm - ',
 '13/01/2026, 6:15\u202fpm - ',
 '13/01/2026, 6:16\u202fpm - ',
 '13/01/2026, 6:21\u202fpm - ',
 '13/01/2026, 6:22\u202fpm - ',
 '13/01/2026, 6:22\u202fpm - ',
 '13/01/2026, 6:22\u202fpm - ',
 '13/01/2026, 6:22\u202fpm - ',
 '13/01/2026, 6:22\u202fpm - ',
 '13/01/2026, 6:22\u202fpm - ',
 '13/01/2026, 10:22\u202fpm - ',
 '13/01/2026, 10:22\u202fpm - ',
 '13/01/2026, 10:22\u202fpm - ',
 '13/01/2026, 10:22\u202fpm - ',
 '13/01/2026, 10:22\u202fpm - ',
 '13/01/2026, 10:22\u202fpm - ',
 '13/01/2026, 10:22\u202fpm - ',
 '13/01/2026, 10:22\u202fpm - ',
 '13/01/2026, 10:22\u202fpm - ',
 '13/01/2026, 10:22\u202fpm - ',
 '13/01/2026, 10:22\u202fpm - ',
 '13/01/2026, 10:22\u202fpm - ',
 '13/01/2026, 10:22\u202fpm - ',
 '13/01/2026, 10:22\u202fpm - ',
 '13/01/2026, 10:22\u202fpm - ',
 '13/01/2026, 10:22\u202fpm - ',
 '13/01/2026, 10:22\u202fpm - ',
 '13/01/2026, 10:23\u202fpm - ',
 '13/01/2026, 10:23\u202fpm - ',
 '13/01/2026, 10:23\u202fpm - ',
 '13/01/2026, 10:23\u202fpm - ',
 '13/01/2026, 10:23\u202fpm - ',
 '13/01/2026, 10:23\u202fpm - ',
 '13/01/2026, 10:23\u202fpm - ',
 '13/01/2026, 10:23\u202fpm - ',
 '13/01/2026, 10:23\u202fpm - ',
 '13/01/2026, 10:23\u202fpm - ',
 '13/01/2026, 10:23\u202fpm - ',
 '13/01/2026, 10:23\u202fpm - ',
 '13/01/2026, 10:23\u202fpm - ',
 '13/01/2026, 10:23\u202fpm - ',
 '13/01/2026, 10:23\u202fpm - ',
 '13/01/2026, 10:23\u202fpm - ',
 '13/01/2026, 10:23\u202fpm - ',
 '13/01/2026, 10:23\u202fpm - ',
 '13/01/2026, 10:23\u202fpm - ',
 '13/01/2026, 10:23\u202fpm - ',
 '13/01/2026, 10:23\u202fpm - ',
 '13/01/2026, 10:23\u202fpm - ',
 '13/01/2026, 10:23\u202fpm - ',
 '13/01/2026, 10:23\u202fpm - ',
 '13/01/2026, 10:29\u202fpm - ',
 '14/01/2026, 11:44\u202fam - ',
 '14/01/2026, 11:45\u202fam - ',
 '14/01/2026, 11:45\u202fam - ',
 '14/01/2026, 2:34\u202fpm - ',
 '14/01/2026, 2:35\u202fpm - ',
 '14/01/2026, 2:35\u202fpm - ',
 '15/01/2026, 7:08\u202fpm - ',
 '15/01/2026, 7:08\u202fpm - ',
 '15/01/2026, 7:08\u202fpm - ',
 '15/01/2026, 7:08\u202fpm - ',
 '15/01/2026, 7:08\u202fpm - ',
 '15/01/2026, 7:08\u202fpm - ',
 '15/01/2026, 7:08\u202fpm - ',
 '15/01/2026, 7:08\u202fpm - ',
 '15/01/2026, 7:08\u202fpm - ',
 '15/01/2026, 7:08\u202fpm - ',
 '15/01/2026, 7:08\u202fpm - ',
 '15/01/2026, 7:47\u202fpm - ',
 '15/01/2026, 7:47\u202fpm - ',
 '15/01/2026, 7:47\u202fpm - ',
 '15/01/2026, 7:47\u202fpm - ',
 '15/01/2026, 7:47\u202fpm - ',
 '15/01/2026, 7:47\u202fpm - ',
 '15/01/2026, 7:47\u202fpm - ',
 '15/01/2026, 7:47\u202fpm - ',
 '15/01/2026, 7:47\u202fpm - ',
 '15/01/2026, 7:47\u202fpm - ',
 '15/01/2026, 7:47\u202fpm - ',
 '15/01/2026, 7:48\u202fpm - ',
 '15/01/2026, 7:49\u202fpm - ',
 '15/01/2026, 7:49\u202fpm - ',
 '15/01/2026, 7:49\u202fpm - ',
 '15/01/2026, 8:05\u202fpm - ',
 '15/01/2026, 8:05\u202fpm - ',
 '15/01/2026, 8:05\u202fpm - ',
 '15/01/2026, 8:05\u202fpm - ',
 '15/01/2026, 8:05\u202fpm - ',
 '15/01/2026, 8:05\u202fpm - ',
 '15/01/2026, 8:05\u202fpm - ',
 '15/01/2026, 8:05\u202fpm - ',
 '15/01/2026, 8:05\u202fpm - ',
 '15/01/2026, 8:05\u202fpm - ',
 '15/01/2026, 8:05\u202fpm - ',
 '15/01/2026, 8:05\u202fpm - ',
 '15/01/2026, 8:05\u202fpm - ',
 '15/01/2026, 8:05\u202fpm - ',
 '15/01/2026, 8:05\u202fpm - ',
 '15/01/2026, 8:05\u202fpm - ',
 '15/01/2026, 8:05\u202fpm - ',
 '15/01/2026, 9:59\u202fpm - ',
 '15/01/2026, 10:02\u202fpm - ',
 '15/01/2026, 10:03\u202fpm - ',
 '15/01/2026, 10:20\u202fpm - ',
 '15/01/2026, 10:21\u202fpm - ',
 '15/01/2026, 10:47\u202fpm - ',
 '15/01/2026, 10:47\u202fpm - ',
 '15/01/2026, 10:48\u202fpm - ',
 '15/01/2026, 10:48\u202fpm - ',
 '15/01/2026, 10:49\u202fpm - ',
 '15/01/2026, 10:49\u202fpm - ',
 '15/01/2026, 10:49\u202fpm - ',
 '15/01/2026, 10:49\u202fpm - ',
 '15/01/2026, 10:49\u202fpm - ',
 '15/01/2026, 10:49\u202fpm - ',
 '15/01/2026, 10:50\u202fpm - ',
 '15/01/2026, 10:54\u202fpm - ',
 '15/01/2026, 10:54\u202fpm - ',
 '15/01/2026, 10:54\u202fpm - ',
 '15/01/2026, 10:54\u202fpm - ',
 '15/01/2026, 10:54\u202fpm - ',
 '15/01/2026, 10:56\u202fpm - ',
 '15/01/2026, 11:05\u202fpm - ',
 '15/01/2026, 11:11\u202fpm - ',
 '15/01/2026, 11:11\u202fpm - ',
 '15/01/2026, 11:11\u202fpm - ',
 '15/01/2026, 11:11\u202fpm - ',
 '15/01/2026, 11:11\u202fpm - ',
 '15/01/2026, 11:11\u202fpm - ',
 '15/01/2026, 11:12\u202fpm - ',
 '15/01/2026, 11:55\u202fpm - ',
 '15/01/2026, 11:55\u202fpm - ',
 '15/01/2026, 11:55\u202fpm - ',
 '15/01/2026, 11:56\u202fpm - ',
 '15/01/2026, 11:57\u202fpm - ',
 '21/01/2026, 6:52\u202fpm - ',
 '21/01/2026, 6:52\u202fpm - ',
 '21/01/2026, 6:53\u202fpm - ',
 '21/01/2026, 6:54\u202fpm - ',
 '21/01/2026, 6:54\u202fpm - ',
 '21/01/2026, 7:07\u202fpm - ',
 '21/01/2026, 7:23\u202fpm - ',
 '21/01/2026, 7:23\u202fpm - ',
 '21/01/2026, 7:23\u202fpm - ',
 '21/01/2026, 7:23\u202fpm - ',
 '21/01/2026, 7:24\u202fpm - ',
 '21/01/2026, 7:25\u202fpm - ',
 '21/01/2026, 7:26\u202fpm - ',
 '21/01/2026, 7:26\u202fpm - ',
 '21/01/2026, 7:26\u202fpm - ',
 '21/01/2026, 7:28\u202fpm - ',
 '21/01/2026, 7:28\u202fpm - ',
 '21/01/2026, 7:28\u202fpm - ',
 '21/01/2026, 7:29\u202fpm - ',
 '21/01/2026, 7:29\u202fpm - ',
 '21/01/2026, 7:29\u202fpm - ',
 '21/01/2026, 7:29\u202fpm - ',
 '21/01/2026, 7:29\u202fpm - ',
 '21/01/2026, 7:29\u202fpm - ',
 '21/01/2026, 7:30\u202fpm - ',
 '21/01/2026, 7:30\u202fpm - ',
 '21/01/2026, 7:30\u202fpm - ',
 '21/01/2026, 7:30\u202fpm - ',
 '21/01/2026, 7:36\u202fpm - ',
 '21/01/2026, 7:40\u202fpm - ',
 '21/01/2026, 7:40\u202fpm - ',
 '21/01/2026, 7:41\u202fpm - ',
 '21/01/2026, 7:45\u202fpm - ',
 '21/01/2026, 7:45\u202fpm - ',
 '21/01/2026, 7:45\u202fpm - ',
 '21/01/2026, 7:45\u202fpm - ',
 '21/01/2026, 7:45\u202fpm - ',
 '21/01/2026, 7:45\u202fpm - ',
 '21/01/2026, 7:47\u202fpm - ',
 '21/01/2026, 7:47\u202fpm - ',
 '21/01/2026, 7:47\u202fpm - ',
 '21/01/2026, 7:47\u202fpm - ',
 '21/01/2026, 7:48\u202fpm - ',
 '21/01/2026, 7:48\u202fpm - ',
 '21/01/2026, 7:48\u202fpm - ',
 '21/01/2026, 7:48\u202fpm - ',
 '21/01/2026, 7:48\u202fpm - ',
 '21/01/2026, 7:48\u202fpm - ',
 '21/01/2026, 7:48\u202fpm - ',
 '21/01/2026, 7:59\u202fpm - ',
 '21/01/2026, 8:33\u202fpm - ',
 '21/01/2026, 8:34\u202fpm - ',
 '21/01/2026, 8:34\u202fpm - ',
 '21/01/2026, 8:34\u202fpm - ',
 '21/01/2026, 8:39\u202fpm - ',
 '21/01/2026, 8:39\u202fpm - ',
 '21/01/2026, 8:39\u202fpm - ',
 '21/01/2026, 8:39\u202fpm - ',
 '21/01/2026, 8:40\u202fpm - ',
 '21/01/2026, 8:50\u202fpm - ',
 '21/01/2026, 8:54\u202fpm - ',
 '21/01/2026, 9:27\u202fpm - ',
 '21/01/2026, 10:07\u202fpm - ',
 '21/01/2026, 10:07\u202fpm - ',
 '21/01/2026, 10:07\u202fpm - ',
 '21/01/2026, 10:07\u202fpm - ',
 '21/01/2026, 10:07\u202fpm - ',
 '21/01/2026, 10:07\u202fpm - ',
 '21/01/2026, 10:08\u202fpm - ',
 '21/01/2026, 10:08\u202fpm - ',
 '21/01/2026, 10:08\u202fpm - ',
 '21/01/2026, 10:08\u202fpm - ',
 '21/01/2026, 10:08\u202fpm - ',
 '21/01/2026, 10:08\u202fpm - ',
 '21/01/2026, 10:08\u202fpm - ',
 '21/01/2026, 10:09\u202fpm - ',
 '21/01/2026, 10:11\u202fpm - ',
 '21/01/2026, 10:21\u202fpm - ',
 '21/01/2026, 10:59\u202fpm - ',
 '21/01/2026, 10:59\u202fpm - ',
 '22/01/2026, 12:39\u202fpm - ',
 '22/01/2026, 12:40\u202fpm - ',
 '22/01/2026, 1:18\u202fpm - ',
 '22/01/2026, 1:18\u202fpm - ',
 '22/01/2026, 1:23\u202fpm - ',
 '22/01/2026, 1:24\u202fpm - ',
 '22/01/2026, 2:03\u202fpm - ',
 '22/01/2026, 2:03\u202fpm - ',
 '22/01/2026, 2:30\u202fpm - ',
 '22/01/2026, 2:48\u202fpm - ',
 '26/01/2026, 12:21\u202fam - ',
 '26/01/2026, 9:09\u202fam - ',
 '26/01/2026, 9:19\u202fam - ',
 '26/01/2026, 9:20\u202fam - ',
 '26/01/2026, 9:20\u202fam - ',
 '26/01/2026, 10:52\u202fam - ',
 '26/01/2026, 12:21\u202fpm - ',
 '26/01/2026, 12:21\u202fpm - ',
 '26/01/2026, 12:22\u202fpm - ',
 '26/01/2026, 12:22\u202fpm - ',
 '26/01/2026, 2:12\u202fpm - ',
 '26/01/2026, 2:12\u202fpm - ',
 '26/01/2026, 2:15\u202fpm - ',
 '26/01/2026, 9:57\u202fpm - ',
 '26/01/2026, 9:57\u202fpm - ',
 '26/01/2026, 10:01\u202fpm - ',
 '26/01/2026, 10:01\u202fpm - ',
 '26/01/2026, 10:03\u202fpm - ',
 '26/01/2026, 10:20\u202fpm - ',
 '26/01/2026, 10:22\u202fpm - ',
 '26/01/2026, 10:22\u202fpm - ',
 '26/01/2026, 10:24\u202fpm - ',
 '26/01/2026, 10:24\u202fpm - ',
 '26/01/2026, 10:25\u202fpm - ',
 '26/01/2026, 10:45\u202fpm - ',
 '26/01/2026, 10:46\u202fpm - ',
 '26/01/2026, 10:48\u202fpm - ',
 '26/01/2026, 10:49\u202fpm - ',
 '26/01/2026, 10:54\u202fpm - ',
 '26/01/2026, 10:54\u202fpm - ',
 '26/01/2026, 11:23\u202fpm - ',
 '27/01/2026, 8:33\u202fpm - ',
 '28/01/2026, 5:19\u202fpm - ',
 '28/01/2026, 5:19\u202fpm - ',
 '28/01/2026, 5:19\u202fpm - ',
 '28/01/2026, 5:19\u202fpm - ',
 '28/01/2026, 5:19\u202fpm - ',
 '28/01/2026, 5:41\u202fpm - ',
 '28/01/2026, 5:41\u202fpm - ',
 '28/01/2026, 5:42\u202fpm - ',
 '28/01/2026, 5:52\u202fpm - ',
 '28/01/2026, 6:28\u202fpm - ',
 '28/01/2026, 6:28\u202fpm - ',
 '29/01/2026, 3:59\u202fpm - ',
 '29/01/2026, 3:59\u202fpm - ',
 '29/01/2026, 3:59\u202fpm - ',
 '29/01/2026, 3:59\u202fpm - ',
 '29/01/2026, 4:03\u202fpm - ',
 '29/01/2026, 4:14\u202fpm - ',
 '30/01/2026, 3:50\u202fpm - ',
 '30/01/2026, 3:50\u202fpm - ',
 '30/01/2026, 3:51\u202fpm - ',
 '30/01/2026, 3:51\u202fpm - ',
 '30/01/2026, 3:52\u202fpm - ',
 '30/01/2026, 3:57\u202fpm - ',
 '30/01/2026, 3:57\u202fpm - ',
 '30/01/2026, 4:03\u202fpm - ',
 '30/01/2026, 4:34\u202fpm - ',
 '31/01/2026, 3:15\u202fpm - ',
 '31/01/2026, 3:26\u202fpm - ',
 '31/01/2026, 6:57\u202fpm - ',
 '01/02/2026, 3:33\u202fpm - ',
 '01/02/2026, 3:33\u202fpm - ',
 '01/02/2026, 3:33\u202fpm - ',
 '01/02/2026, 3:46\u202fpm - ',
 '01/02/2026, 3:46\u202fpm - ',
 '01/02/2026, 3:46\u202fpm - ',
 '01/02/2026, 4:33\u202fpm - ',
 '01/02/2026, 4:34\u202fpm - ',
 '01/02/2026, 4:34\u202fpm - ',
 '01/02/2026, 5:02\u202fpm - ',
 '02/02/2026, 12:10\u202fpm - ',
 '02/02/2026, 12:10\u202fpm - ',
 '02/02/2026, 12:55\u202fpm - ',
 '02/02/2026, 1:22\u202fpm - ',
 '02/02/2026, 1:22\u202fpm - ',
 '02/02/2026, 1:22\u202fpm - ',
 '02/02/2026, 3:11\u202fpm - ',
 '02/02/2026, 3:11\u202fpm - ',
 '02/02/2026, 9:28\u202fpm - ',
 '02/02/2026, 9:28\u202fpm - ',
 '02/02/2026, 9:28\u202fpm - ',
 '02/02/2026, 9:28\u202fpm - ',
 '02/02/2026, 9:28\u202fpm - ',
 '02/02/2026, 9:37\u202fpm - ',
 '02/02/2026, 9:55\u202fpm - ',
 '02/02/2026, 9:55\u202fpm - ',
 '02/02/2026, 10:11\u202fpm - ',
 '02/02/2026, 11:09\u202fpm - ',
 '02/02/2026, 11:10\u202fpm - ',
 '03/02/2026, 4:33\u202fam - ',
 '03/02/2026, 8:50\u202fam - ',
 '03/02/2026, 8:54\u202fam - ',
 '03/02/2026, 11:46\u202fam - ',
 '03/02/2026, 12:00\u202fpm - ',
 '03/02/2026, 2:55\u202fpm - ',
 '03/02/2026, 3:09\u202fpm - ',
 '03/02/2026, 6:40\u202fpm - ',
 '03/02/2026, 7:31\u202fpm - ',
 '03/02/2026, 7:31\u202fpm - ',
 '03/02/2026, 7:31\u202fpm - ',
 '03/02/2026, 7:33\u202fpm - ',
 '03/02/2026, 7:33\u202fpm - ',
 '03/02/2026, 7:37\u202fpm - ',
 '03/02/2026, 7:37\u202fpm - ',
 '03/02/2026, 7:52\u202fpm - ',
 '11/02/2026, 5:23\u202fam - ',
 '11/02/2026, 5:23\u202fam - ',
 '11/02/2026, 5:23\u202fam - ',
 '11/02/2026, 10:20\u202fam - ',
 '11/02/2026, 10:21\u202fam - ',
 '11/02/2026, 12:05\u202fpm - ',
 '11/02/2026, 12:49\u202fpm - ',
 '15/02/2026, 1:15\u202fam - ',
 '15/02/2026, 1:16\u202fam - ',
 '15/02/2026, 1:18\u202fam - ',
 '15/02/2026, 8:43\u202fpm - ',
 '15/02/2026, 8:44\u202fpm - ',
 '15/02/2026, 8:44\u202fpm - ',
 '15/02/2026, 8:45\u202fpm - ',
 '15/02/2026, 8:45\u202fpm - ',
 '15/02/2026, 8:45\u202fpm - ',
 '15/02/2026, 8:47\u202fpm - ',
 '15/02/2026, 8:47\u202fpm - ',
 '15/02/2026, 8:48\u202fpm - ',
 '15/02/2026, 8:48\u202fpm - ',
 '15/02/2026, 8:48\u202fpm - ',
 '15/02/2026, 8:48\u202fpm - ',
 '15/02/2026, 8:49\u202fpm - ',
 '15/02/2026, 8:53\u202fpm - ',
 '15/02/2026, 9:18\u202fpm - ',
 '15/02/2026, 9:18\u202fpm - ',
 '15/02/2026, 9:18\u202fpm - ',
 '15/02/2026, 11:38\u202fpm - ',
 '15/02/2026, 11:56\u202fpm - ',
 '18/02/2026, 7:38\u202fpm - ',
 '18/02/2026, 7:40\u202fpm - ',
 '20/02/2026, 7:41\u202fpm - ',
 '20/02/2026, 7:54\u202fpm - ',
 '20/02/2026, 7:55\u202fpm - ',
 '20/02/2026, 7:55\u202fpm - ',
 '20/02/2026, 8:04\u202fpm - ',
 '20/02/2026, 8:24\u202fpm - ',
 '20/02/2026, 8:24\u202fpm - ',
 '20/02/2026, 8:32\u202fpm - ',
 '20/02/2026, 8:37\u202fpm - ',
 '20/02/2026, 8:43\u202fpm - ',
 '20/02/2026, 8:45\u202fpm - ',
 '20/02/2026, 8:45\u202fpm - ',
 '20/02/2026, 8:45\u202fpm - ',
 '20/02/2026, 8:53\u202fpm - ',
 '20/02/2026, 8:53\u202fpm - ',
 '20/02/2026, 8:54\u202fpm - ',
 '24/02/2026, 8:09\u202fpm - ',
 '24/02/2026, 8:10\u202fpm - ',
 '28/02/2026, 8:46\u202fpm - ',
 '28/02/2026, 8:55\u202fpm - ',
 '11/03/2026, 11:37\u202fam - ',
 '11/03/2026, 11:37\u202fam - ',
 '11/03/2026, 11:37\u202fam - ',
 '11/03/2026, 11:37\u202fam - ',
 '12/03/2026, 10:27\u202fam - ',
 '12/03/2026, 10:28\u202fam - ',
 '12/03/2026, 10:28\u202fam - ',
 '12/03/2026, 10:48\u202fam - ',
 '12/03/2026, 10:49\u202fam - ',
 '16/03/2026, 3:10\u202fpm - ',
 '16/03/2026, 3:10\u202fpm - ',
 '16/03/2026, 3:10\u202fpm - ',
 '16/03/2026, 3:10\u202fpm - ',
 '16/03/2026, 3:11\u202fpm - ',
 '16/03/2026, 3:13\u202fpm - ',
 '16/03/2026, 3:13\u202fpm - ',
 '16/03/2026, 3:13\u202fpm - ',
 '16/03/2026, 3:13\u202fpm - ',
 '16/03/2026, 3:13\u202fpm - ',
 '16/03/2026, 3:14\u202fpm - ',
 '16/03/2026, 3:14\u202fpm - ',
 '16/03/2026, 3:14\u202fpm - ',
 '16/03/2026, 3:14\u202fpm - ',
 '16/03/2026, 3:14\u202fpm - ',
 '16/03/2026, 3:14\u202fpm - ',
 '16/03/2026, 3:14\u202fpm - ',
 '16/03/2026, 3:15\u202fpm - ',
 '16/03/2026, 3:17\u202fpm - ',
 '16/03/2026, 5:52\u202fpm - ',
 '16/03/2026, 5:52\u202fpm - ',
 '16/03/2026, 6:06\u202fpm - ',
 '19/03/2026, 4:09\u202fam - ',
 '19/03/2026, 4:09\u202fam - ',
 '19/03/2026, 4:09\u202fam - ',
 '19/03/2026, 4:09\u202fam - ',
 '19/03/2026, 4:10\u202fam - ',
 '19/03/2026, 4:16\u202fam - ',
 '19/03/2026, 5:08\u202fam - ',
 '19/03/2026, 5:08\u202fam - ',
 '19/03/2026, 5:08\u202fam - ',
 '19/03/2026, 5:08\u202fam - ',
 '19/03/2026, 5:09\u202fam - ',
 '19/03/2026, 5:09\u202fam - ',
 '19/03/2026, 5:09\u202fam - ',
 '19/03/2026, 5:10\u202fam - ',
 '19/03/2026, 5:10\u202fam - ',
 '19/03/2026, 5:10\u202fam - ',
 '19/03/2026, 5:10\u202fam - ',
 '19/03/2026, 5:18\u202fam - ',
 '19/03/2026, 5:18\u202fam - ',
 '19/03/2026, 5:19\u202fam - ',
 '19/03/2026, 5:19\u202fam - ',
 '19/03/2026, 5:42\u202fam - ',
 '20/03/2026, 6:57\u202fpm - ',
 '20/03/2026, 6:57\u202fpm - ',
 '20/03/2026, 6:58\u202fpm - ',
 '20/03/2026, 7:09\u202fpm - ',
 '20/03/2026, 7:14\u202fpm - ',
 '20/03/2026, 8:36\u202fpm - ',
 '21/03/2026, 7:17\u202fam - ',
 '21/03/2026, 7:19\u202fam - ',
 '21/03/2026, 7:20\u202fam - ',
 '21/03/2026, 7:21\u202fam - ',
 '21/03/2026, 7:26\u202fam - ',
 '21/03/2026, 7:26\u202fam - ',
 '21/03/2026, 7:31\u202fam - ',
 '21/03/2026, 7:32\u202fam - ',
 '21/03/2026, 7:38\u202fam - ',
 '21/03/2026, 8:01\u202fam - ',
 '21/03/2026, 8:22\u202fam - ',
 '21/03/2026, 8:22\u202fam - ',
 '21/03/2026, 8:30\u202fam - ',
 '21/03/2026, 8:31\u202fam - ',
 '21/03/2026, 8:31\u202fam - ',

In [10]:
print(len(messages))
print(len(dates))

1285
1285

In [11]:
df=pd.DataFrame({'user_message':messages,'message_date':dates})

In [12]:
df['message_date'] = df['message_date'].str.strip()
df['message_date']=pd.to_datetime(df['message_date'],format='%d/%m/%Y, %I:%M %p -')

In [13]:
df.rename(columns= {'message_date':'date'},inplace=True)

In [14]:
df.head()

                                        user_message                date
0  Messages and calls are end-to-end encrypted. O... 2025-12-09 23:46:00
1        Huzaifa Uet created group "Bacheeeeeeeee"\n 2024-03-04 14:25:00
2                                   You were added\n 2024-03-04 14:25:00
3                                          M_zee: \n 2025-12-10 00:24:00
4                                Ahmad Khan Bbit: \n 2025-12-13 23:10:00

In [15]:
df.shape

(1285, 2)

In [16]:
#sepereate users and  their messages

users = []
messages = []

for message in df['user_message']:
    entry = re.split(r'([\w\W]+?):\s', message)

    if entry[1:]:
        users.append(entry[1])
        messages.append(entry[2])
    else:
        users.append('group_notification')
        messages.append(entry[0])

df['users'] = users
df['messages'] = messages

df.drop(columns=['user_message'], inplace=True)

In [17]:
df.head(10)

,date,users,messages
0,2025-12-09 23:46:00,group_notification,Messages and calls are end-to-end encrypted. O...
1,2024-03-04 14:25:00,group_notification,"Huzaifa Uet created group ""Bacheeeeeeeee""\n"
2,2024-03-04 14:25:00,group_notification,You were added\n
3,2025-12-10 00:24:00,M_zee,\n
4,2025-12-13 23:10:00,Ahmad Khan Bbit,\n
5,2025-12-13 23:10:00,Ahmad Khan Bbit,@⁨Rayan Bbit⁩ @⁨Abdul Rahman Bbit⁩ @⁨M_zee⁩ @⁨...
6,2025-12-14 02:03:00,M_zee,\n
7,2025-12-16 09:39:00,Abdul 🅰️leem Jaat,<Media omitted>\n
8,2025-12-16 09:41:00,Abdul 🅰️leem Jaat,Manni 21\n
9,2025-12-16 09:41:00,Abdul 🅰️leem Jaat,Rayan 24\n

In [18]:
  df['year']=df['date'].dt.year
  df['month']=df['date'].dt.month_name()
  df['day']=df['date'].dt.day
  df['hour']=df['date'].dt.hour
  df['minute']=df['date'].dt.minute

In [19]:
df.head()

,date,users,messages,year,month,day,hour,minute
0,2025-12-09 23:46:00,group_notification,Messages and calls are end-to-end encrypted. O...,2025,December,9,23,46
1,2024-03-04 14:25:00,group_notification,"Huzaifa Uet created group ""Bacheeeeeeeee""\n",2024,March,4,14,25
2,2024-03-04 14:25:00,group_notification,You were added\n,2024,March,4,14,25
3,2025-12-10 00:24:00,M_zee,\n,2025,December,10,0,24
4,2025-12-13 23:10:00,Ahmad Khan Bbit,\n,2025,December,13,23,10